pipeline:
  name: DotNet Build Deploy Pipeline
  identifier: dotnet_build_deploy_pipeline
  orgIdentifier: default
  projectIdentifier: spark
  tags: {}
  template:
    templateRef: account.DotNet_Build_Deploy_Pipeline
    versionLabel: v1
    templateInputs:
      variables:
        - name: APP_NAME
          value: <+input>
        - name: LANGUAGE_VERSION
          value: <+input>
        - name: DR_ENABLED
          value: <+input>
        - name: GITOPS_APP_NAME
          value: <+input>
        - name: NOTIFICATION_EMAIL
          value: <+input>
      properties:
        ci:
          codebase:
            repoName: <+input>
            build: <+input>
      stages:
        - stage:
            identifier: build
            template:
              templateInputs:
                variables:
                  - name: DOCKER_FILE
                    value: <+input>
        - parallel:
            - stage:
                identifier: Deploy_DEV
                template:
                  templateInputs:
                    variables:
                      - name: STAGE_ENABLED
                        value: <+input>.default(true)
                      - name: GITOPS_APP_NAME
                        value: <+input>.default(<+pipeline.variables.GITOPS_APP_NAME>)
                    spec:
                      service:
                        serviceRef: <+input>
                        serviceInputs: <+input>
                      execution:
                        steps:
                          - step:
                              identifier: updateReleaseRepo
                              spec:
                                variables:
                                  - name: image.tag
                                    value: <+input>
                          - step:
                              identifier: QA_Approval
                              spec:
                                approvers:
                                  userGroups: <+input>
                      environment:
                        environmentRef: <+input>
                        deployToAll: <+input>
                        environmentInputs: <+input>
                        gitOpsClusters: <+input>
        - stage:
            identifier: Deploy_QA
            template:
              templateInputs:
                variables:
                  - name: STAGE_ENABLED
                    value: <+input>.default(true)
                  - name: GITOPS_APP_NAME
                    value: <+input>.default(<+pipeline.variables.GITOPS_APP_NAME>)
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: updateReleaseRepo
                          spec:
                            variables:
                              - name: image.tag
                                value: <+input>
                      - step:
                          identifier: QA_Approval
                          spec:
                            approvers:
                              userGroups: <+input>
                  environment:
                    environmentRef: <+input>
                    deployToAll: <+input>
                    environmentInputs: <+input>
                    gitOpsClusters: <+input>
        - stage:
            identifier: release
            template:
              templateInputs:
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: Generate_Version
                          spec:
                            envVariables:
                              RELEASE_TAG: <+input>.executionInput().default(<+execution.steps.Increment_Version.output.outputVariables.RELEASE_VERSION>).regex((v\d{0,4}\.\d{0,4}\.\d{0,4}|<\+execution.steps.Increment_Version.output.outputVariables.RELEASE_VERSION>))
        - stage:
            identifier: Deploy_STG
            template:
              templateInputs:
                variables:
                  - name: STAGE_ENABLED
                    value: <+input>.default(true)
                  - name: GITOPS_APP_NAME
                    value: <+input>.default(<+pipeline.variables.GITOPS_APP_NAME>)
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: updateReleaseRepo
                          spec:
                            variables:
                              - name: image.tag
                                value: <+input>
                      - step:
                          identifier: QA_Approval
                          spec:
                            approvers:
                              userGroups: <+input>
                  environment:
                    environmentRef: <+input>
                    deployToAll: <+input>
                    environmentInputs: <+input>
                    gitOpsClusters: <+input>
        - stage:
            identifier: Change_Management
            template:
              templateInputs:
                variables:
                  - name: CHG_OR_INC_NUMBER
                    value: <+input>.executionInput()
        - stage:
            identifier: Deploy_PRD
            template:
              templateInputs:
                variables:
                  - name: STAGE_ENABLED
                    value: <+input>.default(true)
                  - name: GITOPS_APP_NAME
                    value: <+input>.default(<+pipeline.variables.GITOPS_APP_NAME>)
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: updateReleaseRepo
                          spec:
                            variables:
                              - name: image.tag
                                value: <+input>
                      - step:
                          identifier: QA_Approval
                          spec:
                            approvers:
                              userGroups: <+input>
                  environment:
                    environmentRef: <+input>
                    deployToAll: <+input>
                    environmentInputs: <+input>
                    gitOpsClusters: <+input>
        - stage:
            identifier: Deploy_DR
            template:
              templateInputs:
                variables:
                  - name: STAGE_ENABLED
                    value: <+input>.default(true)
                  - name: GITOPS_APP_NAME
                    value: <+input>.default(<+pipeline.variables.GITOPS_APP_NAME>)
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: updateReleaseRepo
                          spec:
                            variables:
                              - name: image.tag
                                value: <+input>
                      - step:
                          identifier: QA_Approval
                          spec:
                            approvers:
                              userGroups: <+input>
                  environment:
                    environmentRef: <+input>
                    deployToAll: <+input>
                    environmentInputs: <+input>
                    gitOpsClusters: <+input>
